---
- name: "SCORED | 3.1.1 | PATCH | Ensure IP forwarding is disabled"
  sysctl:
      name: net.ipv4.ip_forward
      value: 0
      state: present
      reload: true
      ignoreerrors: true
  when:
      - ubuntu1604cis_rule_3_1_1
      - not ubuntu1604cis_is_router
  notify:
      - sysctl flush ipv4 route table
  tags:
      - level1
      - scored
      - patch
      - sysctl
      - rule_3.1.1

- name: "SCORED | 3.1.2 | PATCH | Ensure packet redirect sending is disabled"
  sysctl:
      name: '{{ item.name }}'
      value: '{{ item.value }}'
      sysctl_set: true
      state: present
      reload: true
      ignoreerrors: true
  with_items:
      - { name: net.ipv4.conf.all.send_redirects, value: 0 }
      - { name: net.ipv4.conf.default.send_redirects, value: 0 }
  when:
      - ubuntu1604cis_rule_3_1_2
      - not ubuntu1604cis_is_router
  notify:
      - sysctl flush ipv4 route table
  tags:
      - level1
      - scored
      - patch
      - sysctl
      - rule_3.1.2

- name: "SCORED | 3.2.1 | PATCH | Ensure source routed packets are not accepted"
  sysctl:
      name: '{{ item.name }}'
      value: '{{ item.value }}'
      sysctl_set: true
      state: present
      reload: true
      ignoreerrors: true
  with_items:
      - { name: net.ipv4.conf.all.accept_source_route, value: 0 }
      - { name: net.ipv4.conf.default.accept_source_route, value: 0 }
  when:
      - ubuntu1604cis_rule_3_2_1
  notify:
      - sysctl flush ipv4 route table
  tags:
      - level1
      - scored
      - patch
      - sysctl
      - rule_3.2.1

- name: "SCORED | 3.2.2 | PATCH | Ensure ICMP redirects are not accepted"
  sysctl:
      name: '{{ item.name }}'
      value: '{{ item.value }}'
      sysctl_set: true
      state: present
      reload: true
      ignoreerrors: true
  with_items:
      - { name: net.ipv4.conf.all.accept_redirects, value: 0 }
      - { name: net.ipv4.conf.default.accept_redirects, value: 0 }
  when:
      - ubuntu1604cis_rule_3_2_2
  notify:
      - sysctl flush ipv4 route table
  tags:
      - level1
      - scored
      - patch
      - sysctl
      - rule_3.2.2

- name: "SCORED | 3.2.3 | PATCH | Ensure secure ICMP redirects are not accepted"
  sysctl:
      name: '{{ item.name }}'
      value: '{{ item.value }}'
      sysctl_set: true
      state: present
      reload: true
      ignoreerrors: true
  with_items:
      - { name: net.ipv4.conf.all.secure_redirects, value: 0 }
      - { name: net.ipv4.conf.default.secure_redirects, value: 0 }
  when:
      - ubuntu1604cis_rule_3_2_3
  notify:
      - sysctl flush ipv4 route table
  tags:
      - level1
      - scored
      - patch
      - sysctl
      - rule_3.2.3

- name: "SCORED | 3.2.4 | PATCH | Ensure suspicious packets are logged"
  sysctl:
      name: '{{ item.name }}'
      value: '{{ item.value }}'
      sysctl_set: true
      state: present
      reload: true
      ignoreerrors: true
  with_items:
      - { name: net.ipv4.conf.all.log_martians, value: 1 }
      - { name: net.ipv4.conf.default.log_martians, value: 1 }
  when:
      - ubuntu1604cis_rule_3_2_4
  notify:
      - sysctl flush ipv4 route table
  tags:
      - level1
      - scored
      - patch
      - sysctl
      - rule_3.2.4

- name: "SCORED | 3.2.5 | PATCH | Ensure broadcast ICMP requests are ignored"
  sysctl:
      name: net.ipv4.icmp_echo_ignore_broadcasts
      value: 1
      state: present
      reload: true
      ignoreerrors: true
  when:
      - ubuntu1604cis_rule_3_2_5
  notify:
      - sysctl flush ipv4 route table
  tags:
      - level1
      - scored
      - patch
      - sysctl
      - rule_3.2.5

- name: "SCORED | 3.2.6 | PATCH | Ensure bogus ICMP responses are ignored"
  sysctl:
      name: net.ipv4.icmp_ignore_bogus_error_responses
      value: 1
      state: present
      reload: true
      ignoreerrors: true
  when:
      - ubuntu1604cis_rule_3_2_6
  notify:
      - sysctl flush ipv4 route table
  tags:
      - level1
      - scored
      - patch
      - sysctl
      - rule_3.2.6

- name: "SCORED | 3.2.7 | PATCH | Ensure Reverse Path Filtering is enabled"
  sysctl:
      name: '{{ item.name }}'
      value: '{{ item.value }}'
      sysctl_set: true
      state: present
      reload: true
      ignoreerrors: true
  with_items:
      - { name: net.ipv4.conf.all.rp_filter, value: 1 }
      - { name: net.ipv4.conf.default.rp_filter, value: 1 }
  when:
      - ubuntu1604cis_rule_3_2_7
  notify:
      - sysctl flush ipv4 route table
  tags:
      - level1
      - scored
      - patch
      - sysctl
      - rule_3.2.7

- name: "SCORED | 3.2.8 | PATCH | Ensure TCP SYN Cookies is enabled"
  sysctl:
      name: net.ipv4.tcp_syncookies
      value: 1
      state: present
      reload: true
      ignoreerrors: true
  when:
      - ubuntu1604cis_rule_3_2_8
  notify:
      - sysctl flush ipv4 route table
  tags:
      - level1
      - scored
      - patch
      - sysctl
      - rule_3.2.8

- name: "SCORED | 3.3.1 | PATCH | Ensure IPv6 router advertisements are not accepted"
  sysctl:
      name: '{{ item.name }}'
      value: '{{ item.value }}'
      sysctl_set: true
      state: present
      reload: true
      ignoreerrors: true
  with_items:
      - { name: net.ipv6.conf.all.accept_ra, value: 0 }
      - { name: net.ipv6.conf.default.accept_ra, value: 0 }
  when:
      - ubuntu1604cis_rule_3_3_1
      - ubuntu1604cis_ipv6_required
  notify:
      - sysctl flush ipv6 route table
  tags:
      - level1
      - scored
      - patch
      - sysctl
      - rule_3.3.1

- name: "SCORED | 3.3.2 | PATCH | Ensure IPv6 redirects are not accepted"
  sysctl:
      name: '{{ item.name }}'
      value: '{{ item.value }}'
      sysctl_set: true
      state: present
      reload: true
      ignoreerrors: true
  with_items:
      - { name: net.ipv6.conf.all.accept_redirects, value: 0 }
      - { name: net.ipv6.conf.default.accept_redirects, value: 0 }
  when:
      - ubuntu1604cis_rule_3_3_2
      - ubuntu1604cis_ipv6_required
  notify:
      - sysctl flush ipv6 route table
  tags:
      - level1
      - scored
      - patch
      - sysctl
      - rule_3.3.2

- name: "NOTSCORED | 3.3.3 | PATCH | Ensure IPv6 is disabled"
  lineinfile:
      dest: /etc/modprobe.d/CIS.conf
      regexp: "^(#)?options ipv6 disable="
      line: "options ipv6 disable=1"
      create: true
  when:
      - ubuntu1604cis_rule_3_3_3
      - not ubuntu1604cis_ipv6_required
  tags:
      - level1
      - notscored
      - patch
      - rule_3.3.3

- name: "SCORED | 3.4.1 | PATCH | Ensure TCP Wrappers is installed"
  apt:
      name: "{{ tcp_wrapper_package[ansible_os_family] }}"
      state: present
      install_recommends: false
  when:
      - ubuntu1604cis_rule_3_4_1
  tags:
      - level1
      - scored
      - patch
      - rule_3.4.1

- name: "SCORED | 3.4.2 | PATCH | Ensure /etc/hosts.allow is configured"
  template:
      src: hosts.allow.j2
      dest: /etc/hosts.allow
      owner: root
      group: root
      mode: 0644
  when:
      - ubuntu1604cis_rule_3_4_2
  tags:
      - level1
      - scored
      - patch
      - rule_3.4.2

- name: "SCORED | 3.4.3 | PATCH | Ensure /etc/hosts.deny is configured"
  lineinfile:
      dest: /etc/hosts.deny
      regexp: "^(#)?ALL"
      line: "ALL: ALL"
  when:
      - ubuntu1604cis_rule_3_4_3
  tags:
      - level1
      - scored
      - patch
      - rule_3.4.3

- name: "SCORED | 3.4.4 | PATCH | Ensure permissions on /etc/hosts.allow are configured"
  file:
      dest: /etc/hosts.allow
      owner: root
      group: root
      mode: 0644
  when:
      - ubuntu1604cis_rule_3_4_4
  tags:
      - level1
      - scored
      - patch
      - rule_3.4.4

- name: "SCORED | 3.4.5 | PATCH | Ensure permissions on /etc/hosts.deny are 644"
  file:
      dest: /etc/hosts.deny
      owner: root
      group: root
      mode: 0644
  when:
      - ubuntu1604cis_rule_3_4_5
  tags:
      - level1
      - scored
      - patch
      - rule_3.4.5

- name: "NOTSCORED | 3.5.1 | PATCH | Ensure DCCP is disabled"
  lineinfile:
      dest: /etc/modprobe.d/CIS.conf
      regexp: "^(#)?install dccp(\\s|$)"
      line: "install dccp /bin/true"
      create: true
  when:
      - ubuntu1604cis_rule_3_5_1
  tags:
      - level1
      - notscored
      - patch
      - rule_3.5.1

- name: "NOTSCORED | 3.5.2 | PATCH | Ensure SCTP is disabled"
  lineinfile:
      dest: /etc/modprobe.d/CIS.conf
      regexp: "^(#)?install sctp(\\s|$)"
      line: "install sctp /bin/true"
      create: true
  when:
      - ubuntu1604cis_rule_3_5_2
  tags:
      - level1
      - notscored
      - patch
      - rule_3.5.2

- name: "NOTSCORED | 3.5.3 | PATCH | Ensure RDS is disabled"
  lineinfile:
      dest: /etc/modprobe.d/CIS.conf
      regexp: "^(#)?install rds(\\s|$)"
      line: "install rds /bin/true"
      create: true
  when:
      - ubuntu1604cis_rule_3_5_3
  tags:
      - level1
      - notscored
      - patch
      - rule_3.5.3

- name: "NOTSCORED | 3.5.4 | PATCH | Ensure TIPC is disabled"
  lineinfile:
      dest: /etc/modprobe.d/CIS.conf
      regexp: "^(#)?install tipc(\\s|$)"
      line: "install tipc /bin/true"
      create: true
  when:
      - ubuntu1604cis_rule_3_5_4
  tags:
      - level1
      - notscored
      - patch
      - rule_3.5.4

- name: "SCORED | 3.6 | PATCH | Ensure firewalld is installed and started | CUSTOM"
  apt:
      name: firewalld
      state: enabled
      install_recommends: false
  when:
      - ubuntu1604cis_firewall == "firewalld"
      - ubuntu1604cis_setup_firewall
  tags:
      - level1
      - scored
      - patch
      - rule_3.6


- name: "SCORED | 3.6.1 | PATCH | Ensure iptables is installed and started"
  apt:
      name: "{{ item }}"
      update_cache: true
      state: present
  with_items:
      - 'iptables'
      - 'iptables-persistent'
  when:
      - ubuntu1604cis_rule_3_6_1
  tags:
      - level1
      - scored
      - patch
      - rule_3.6.1

- name: "SCORED | 3.6.2 | PATCH | Ensure default deny firewall policy"
  lineinfile:
      dest: /etc/firewalld/firewalld.conf
      regexp: "^DefaultZone"
      line: "DefaultZone=drop"
  when:
      - ubuntu1604cis_firewall == "firewalld"
      - ubuntu1604cis_setup_firewall
  tags:
      - level1
      - scored
      - patch
      - rule_3.6.2

- name: "SCORED | 3.6.2 | PATCH | Ensure default deny firewall policy"
  firewalld:
      state: enabled
      zone: drop
      permanent: true
  when:
      - ubuntu1604cis_firewall == "firewalld"
      - ubuntu1604cis_setup_firewall
  tags:
      - level1
      - scored
      - patch
      - rule_3.6.2

- name: "SCORED | 3.6 | PATCH | Ensure ufw is installed and started | CUSTOM"
  systemd:
      name: "ufw"
      state: started
      enabled: true
  when:
      - ubuntu1604cis_firewall == "ufw"
      - ubuntu1604cis_setup_firewall
  tags:
      - level1
      - scored
      - patch

- name: "SCORED | 3.6 | PATCH | Ensure ufw is configured | CUSTOM"
  command: "{{ item }}"
  with_items:
    - "ufw reset"
    - "ufw default deny incoming"
    - "ufw default allow outgoing"
    - "ufw allow ssh"
    - "ufw allow smtp"
    - "ufw allow http"
    - "ufw allow https"
    - "ufw enable"
  when:
      - ubuntu1604cis_firewall == "ufw"
      - ubuntu1604cis_setup_firewall
  tags:
      - level1
      - scored
      - patch
  become: true

- name: "SCORED | 3.6.2 | PATCH | Ensure default deny firewall policy"
  lineinfile:
      name: "{{ iptables_rules_file }}"
      line: "{{ item }}"
      insertbefore: '^COMMIT'
      regexp: "^{{ item }}"
      create: yes
  with_items:
      - '-P INPUT DROP'
      - '-P FORWARD DROP'
      - '-P OUTPUT DROP'
  when:
      - ubuntu1604cis_rule_3_6_3
  notify: restart iptables
  tags:
      - level1
      - scored
      - patch
      - rule_3.6.2

- name: "SCORED | 3.6.3 | PATCH | Ensure loopback traffic is configured"
  lineinfile:
      name: "{{ iptables_rules_file }}"
      line: "{{ item }}"
      insertbefore: '^COMMIT'
      regexp: "^{{ item }}"
      create: yes
  with_items:
      - '-A INPUT -i lo -j ACCEPT'
      - '-A OUTPUT -o lo -j ACCEPT'
      - '-A INPUT -s 127.0.0.0/8 -j DROP'
  when:
      - ubuntu1604cis_rule_3_6_3
  notify: restart iptables
  tags:
      - level1
      - scored
      - patch
      - rule_3.6.3

- name: "NOTSCORED | 3.6.4 | PATCH | Ensure outbound and established connections are configured"
  lineinfile:
      name: "{{ iptables_rules_file }}"
      line: "{{ item }}"
      insertbefore: '^COMMIT'
      regexp: "^{{ item }}"
      create: yes
  with_items:
      - '-A OUTPUT -p tcp -m state --state NEW,ESTABLISHED -j ACCEPT'
      - '-A OUTPUT -p udp -m state --state NEW,ESTABLISHED -j ACCEPT'
      - '-A OUTPUT -p icmp -m state --state NEW,ESTABLISHED -j ACCEPT'
      - '-A INPUT -p tcp -m state --state ESTABLISHED -j ACCEPT'
      - '-A INPUT -p udp -m state --state ESTABLISHED -j ACCEPT'
      - '-A INPUT -p icmp -m state --state ESTABLISHED -j ACCEPT'
  when:
      - ubuntu1604cis_rule_3_6_4
  notify: restart iptables
  tags:
      - level1
      - notscored
      - patch
      - rule_3.6.4

- name: "SCORED | 3.6.5 | PATCH | Ensure firewall rules exist for all open ports"
  shell: |
      UDP=$(lsof -i -P -n | grep -e UDP | awk '{print $9}' | cut -d ":" -f2 | sort | uniq)
      if [ -n "$UDP" ]; then
        for i in $UDP ; do
          iptables -C INPUT -p udp --dport $i -m state --state NEW -j ACCEPT ;
            if [ $? -ne 0 ] ; then
              sed -i '/^:OUTPUT.*/a -A INPUT -p udp --dport '$i' -m state --state NEW -j ACCEPT' /etc/iptables/rules.v4 ;
            fi
        done
      fi

      TCP=$(lsof -i -P -n | grep -e LISTEN | awk '{print $9}' | cut -d ":" -f2 | sort | uniq)
      if [ -n "$TCP" ]; then
        for i in $TCP ; do
          iptables -C INPUT -p tcp --dport $i -m state --state NEW -j ACCEPT ;
            if [ $? -ne 0 ] ; then
              sed -i '/^:OUTPUT.*/a -A INPUT -p tcp --dport '$i' -m state --state NEW -j ACCEPT' /etc/iptables/rules.v4 ;
            fi
        done
      fi
  args:
      executable: /bin/bash
  when:
      - ubuntu1604cis_rule_3_6_5
  notify: restart iptables
  tags:
      - level1
      - scored
      - patch
      - rule_3.6.5

- name: "NOTSCORED | 3.7 | PATCH | Ensure wireless interfaces are disabled"
  apt:
      name: rfkill
      state: present
  when:
      - ubuntu1604cis_rule_3_7
  tags:
      - level1
      - notscored
      - patch
      - rule_3.7

- name: "NOTSCORED | 3.7 | PATCH | Ensure wireless interfaces are disabled"
  command: rfkill block wifi
  when:
      - ubuntu1604cis_rule_3_7
  tags:
      - level1
      - notscored
      - patch
      - rule_3.7
